# Generated by Django 4.1.7 on 2023-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Google_Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=250, null=True)),
                ("patent_num", models.CharField(blank=True, max_length=250, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("classification", models.TextField(blank=True, null=True)),
                ("claims", models.TextField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("background", models.TextField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("tech_field", models.TextField(blank=True, null=True)),
                ("drawing", models.TextField(blank=True, null=True)),
                ("detail_desc", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "google_patent",
                "verbose_name_plural": "google_patents",
                "db_table": "google_patent",
            },
        ),
    ]
