# Generated by Django 4.1.7 on 2023-04-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="google_patent",
            name="assignee",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="google_patent",
            name="date",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="google_patent",
            name="inventor",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
